# Generated by Django 4.0.5 on 2022-08-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0004_mediafile_mediafile_theory_medi_content_219507_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
