# Generated by Django 4.0.5 on 2022-09-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиафайлы'},
        ),
    ]
