# Generated by Django 4.0.5 on 2022-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teachers',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
    ]
