# Generated by Django 4.0.5 on 2022-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время вождения'),
        ),
    ]
