# Generated by Django 4.0.5 on 2022-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(to='teacher.teacher', verbose_name='Владелец'),
        ),
    ]
